kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: gradioapp
  labels:
    app: gradioapp
spec:
  path: /
  to:
    kind: Service
    name: gradioapp-svc
    weight: 100
  port:
    targetPort: 7860
  tls:
    termination: edge
  wildcardPolicy: None
