kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: gradioapp
  labels:
    app: gradioapp
spec:
  to:
    kind: Service
    name: gradioapp-svc
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    destinationCACertificate: ""
  port:
    targetPort: 7860
